### PR TITLE
Highlighter now works on the whole line.

### PR DESCRIPTION
**Pull request by mkrueger**
I know "no new features" so let's see that as a possible improvement for future versions.
The Highlighting interface works on tokens but for my use case I need context sensitive highlighting so it needs to work on the whole line and the highlighter to tokenize the line.

I moved the word highlighting to WordHighlighter so consuming code using that doesn't break.

### CODE REVIEW

**Review by patriksvensson — APPROVED** [review]
LGTM 👍

**Comment by patriksvensson** [comment]
I said that too soon. Seems like there is some stylecop problem. Would you mind fixing snd I'll get this merged and a new version released asap.

**Comment by mkrueger** [comment]
fixed - missed that.

I've another change I needed regarding to the completion where I ran into similar issues.
I'll make an extra PR about it. I need to review it.

**Comment by patriksvensson** [comment]
Merged! Thank you for your contribution. Much appreciated! 👍
I will release a new version with this commit include.

**Pull request merged**
